import 'package:flutter/material.dart';

class StyleString {
  static const double cardSpace = 8;
  static const double safeSpace = 12;
  static BorderRadius mdRadius = BorderRadius.circular(10);
  static const Radius imgRadius = Radius.circular(10);
  static const double aspectRatio = 16 / 10;
}

class Constants {
  // 27eb53fc9058f8c3  移动端 Android
  // 4409e2ce8ffd12b8  HD版
  static const String appKey = 'dfca71928277209b';
  // 59b43e04ad6965f34319062b478f83dd TV端
  static const String appSec = 'b5475a8825547a4fc26c7d518eaaa02e';
  static const String thirdSign = '04224646d1fea004e79606d3b038c84a';
  static const String thirdApi =
      'https://www.mcbbs.net/template/mcbbs/image/special_photo_bg.png';

  static const String traceId =
      '11111111111111111111111111111111:1111111111111111:0:0';
  static const String userAgent =
  'Mozilla/5.0 BiliDroid/1.46.2 (bbcallen@gmail.com) os/android model/vivo mobi_app/android_hd build/2001100 channel/yingyongbao innerVer/2001100 osVer/14 network/2';
  static const String statistics = '%7B%22appId%22%3A5%2C%22platform%22%3A3%2C%22version%22%3A%221.46.2%22%2C%22abtest%22%3A%22%22%7D';
  //Uri.encodeComponent('{"appId": 5,"platform": 3,"version": "1.46.2","abtest": ""}');

  //内容来自 https://passport.bilibili.com/web/generic/country/list
  static const List<Map<String, dynamic>> internationalDialingPrefix = [
    {"id": 1, "cname": "Mainland China", "country_id": "86"},
    {"id": 5, "cname": "Hong Kong SAR", "country_id": "852"},
    {"id": 2, "cname": "Macau SAR", "country_id": "853"},
    {"id": 3, "cname": "Taiwan", "country_id": "886"},
    {"id": 4, "cname": "United States", "country_id": "1"},
    {"id": 6, "cname": "Belgium", "country_id": "32"},
    {"id": 7, "cname": "Australia", "country_id": "61"},
    {"id": 8, "cname": "France", "country_id": "33"},
    {"id": 9, "cname": "Canada", "country_id": "1"},
    {"id": 10, "cname": "Japan", "country_id": "81"},
    {"id": 11, "cname": "Singapore", "country_id": "65"},
    {"id": 12, "cname": "South Korea", "country_id": "82"},
    {"id": 13, "cname": "Malaysia", "country_id": "60"},
    {"id": 14, "cname": "United Kingdom", "country_id": "44"},
    {"id": 15, "cname": "Italy", "country_id": "39"},
    {"id": 16, "cname": "Germany", "country_id": "49"},
    {"id": 18, "cname": "Russia", "country_id": "7"},
    {"id": 19, "cname": "New Zealand", "country_id": "64"}, //common:1-19
    {"id": 153, "cname": "Wallis and Futuna", "country_id": "1681"},
    {"id": 152, "cname": "Portugal", "country_id": "351"},
    {"id": 151, "cname": "Palau", "country_id": "680"},
    {"id": 150, "cname": "Norfolk Island", "country_id": "672"},
    {"id": 149, "cname": "Norway", "country_id": "47"},
    {"id": 148, "cname": "Niue", "country_id": "683"},
    {"id": 147, "cname": "Nigeria", "country_id": "234"},
    {"id": 146, "cname": "Niger", "country_id": "227"},
    {"id": 145, "cname": "Nicaragua", "country_id": "505"},
    {"id": 144, "cname": "Nepal", "country_id": "977"},
    {"id": 143, "cname": "Nauru", "country_id": "674"},
    {"id": 154, "cname": "Georgia", "country_id": "995"},
    {"id": 155, "cname": "Sweden", "country_id": "46"},
    {"id": 165, "cname": "Saudi Arabia", "country_id": "966"},
    {"id": 164, "cname": "Zanzibar", "country_id": "259"},
    {"id": 163, "cname": "Seychelles", "country_id": "248"},
    {"id": 162, "cname": "Cyprus", "country_id": "357"},
    {"id": 161, "cname": "Senegal", "country_id": "221"},
    {"id": 160, "cname": "Sierra Leone", "country_id": "232"},
    {"id": 159, "cname": "American Samoa", "country_id": "684"},
    {"id": 158, "cname": "Samoa", "country_id": "685"},
    {"id": 157, "cname": "El Salvador", "country_id": "503"},
    {"id": 156, "cname": "Switzerland", "country_id": "41"},
    {"id": 166, "cname": "São Tomé and Príncipe", "country_id": "239"},
    {"id": 142, "cname": "Serbia", "country_id": "381"},
    {"id": 141, "cname": "South Africa", "country_id": "27"},
    {"id": 128, "cname": "Mauritania", "country_id": "222"},
    {"id": 127, "cname": "Mauritius", "country_id": "230"},
    {"id": 126, "cname": "Marshall Islands", "country_id": "692"},
    {"id": 125, "cname": "Martinique", "country_id": "596"},
    {"id": 124, "cname": "North Macedonia", "country_id": "389"},
    {"id": 123, "cname": "Northern Mariana Islands", "country_id": "1670"},
    {"id": 122, "cname": "Mali", "country_id": "223"},
    {"id": 121, "cname": "Malawi", "country_id": "265"},
    {"id": 120, "cname": "Malta", "country_id": "356"},
    {"id": 119, "cname": "Maldives", "country_id": "960"},
    {"id": 129, "cname": "Mongolia", "country_id": "976"},
    {"id": 130, "cname": "Montserrat", "country_id": "1664"},
    {"id": 140, "cname": "Namibia", "country_id": "264"},
    {"id": 139, "cname": "Mexico", "country_id": "52"},
    {"id": 138, "cname": "Mozambique", "country_id": "258"},
    {"id": 137, "cname": "Monaco", "country_id": "377"},
    {"id": 136, "cname": "Morocco", "country_id": "212"},
    {"id": 135, "cname": "Moldova", "country_id": "373"},
    {"id": 134, "cname": "Myanmar", "country_id": "95"},
    {"id": 133, "cname": "Micronesia", "country_id": "691"},
    {"id": 132, "cname": "Peru", "country_id": "51"},
    {"id": 131, "cname": "Bangladesh", "country_id": "880"},
    {"id": 118, "cname": "Madagascar", "country_id": "261"},
    {"id": 167, "cname": "Saint Lucia", "country_id": "1784"},
    {"id": 216, "cname": "Chile", "country_id": "56"},
    {"id": 203, "cname": "Jamaica", "country_id": "1876"},
    {"id": 202, "cname": "Syria", "country_id": "963"},
    {"id": 201, "cname": "Hungary", "country_id": "36"},
    {"id": 200, "cname": "Côte d'Ivoire", "country_id": "225"},
    {"id": 199, "cname": "Greece", "country_id": "30"},
    {"id": 198, "cname": "Spain", "country_id": "34"},
    {"id": 197, "cname": "Uzbekistan", "country_id": "998"},
    {"id": 196, "cname": "Uruguay", "country_id": "598"},
    {"id": 195, "cname": "Ukraine", "country_id": "380"},
    {"id": 194, "cname": "Uganda", "country_id": "256"},
    {"id": 204, "cname": "Armenia", "country_id": "374"},
    {"id": 205, "cname": "Yemen", "country_id": "967"},
    {"id": 215, "cname": "Gibraltar", "country_id": "350"},
    {"id": 214, "cname": "Chad", "country_id": "235"},
    {"id": 213, "cname": "Zambia", "country_id": "260"},
    {"id": 212, "cname": "Vietnam", "country_id": "84"},
    {"id": 211, "cname": "Jordan", "country_id": "962"},
    {"id": 210, "cname": "Indonesia", "country_id": "62"},
    {"id": 209, "cname": "India", "country_id": "91"},
    {"id": 208, "cname": "Israel", "country_id": "972"},
    {"id": 207, "cname": "Iran", "country_id": "98"},
    {"id": 206, "cname": "Iraq", "country_id": "964"},
    {"id": 193, "cname": "Brunei", "country_id": "673"},
    {"id": 192, "cname": "Venezuela", "country_id": "58"},
    {"id": 191, "cname": "British Virgin Islands", "country_id": "1284"},
    {"id": 178, "cname": "Thailand", "country_id": "66"},
    {"id": 177, "cname": "Somalia", "country_id": "252"},
    {"id": 176, "cname": "Solomon Islands", "country_id": "677"},
    {"id": 175, "cname": "Suriname", "country_id": "597"},
    {"id": 174, "cname": "Sudan", "country_id": "249"},
    {"id": 173, "cname": "Eswatini", "country_id": "268"},
    {"id": 172, "cname": "Slovenia", "country_id": "386"},
    {"id": 171, "cname": "Slovakia", "country_id": "421"},
    {"id": 170, "cname": "Sri Lanka", "country_id": "94"},
    {"id": 169, "cname": "Saint Pierre and Miquelon", "country_id": "508"},
    {"id": 179, "cname": "Tanzania", "country_id": "255"},
    {"id": 180, "cname": "Tonga", "country_id": "676"},
    {"id": 190, "cname": "US Virgin Islands", "country_id": "1340"},
    {"id": 189, "cname": "Vanuatu", "country_id": "678"},
    {"id": 188, "cname": "Tokelau", "country_id": "690"},
    {"id": 187, "cname": "Turkmenistan", "country_id": "993"},
    {"id": 186, "cname": "Turkey", "country_id": "90"},
    {"id": 185, "cname": "Tuvalu", "country_id": "688"},
    {"id": 184, "cname": "Tunisia", "country_id": "216"},
    {"id": 183, "cname": "Ascension Island", "country_id": "247"},
    {"id": 182, "cname": "Trinidad and Tobago", "country_id": "1868"},
    {"id": 181, "cname": "Turks and Caicos", "country_id": "1649"},
    {"id": 168, "cname": "San Marino", "country_id": "378"},
    {"id": 67, "cname": "French Guiana", "country_id": "594"},
    {"id": 54, "cname": "Bhutan", "country_id": "975"},
    {"id": 53, "cname": "Botswana", "country_id": "267"},
    {"id": 52, "cname": "Belize", "country_id": "501"},
    {"id": 51, "cname": "Bolivia", "country_id": "591"},
    {"id": 50, "cname": "Poland", "country_id": "48"},
    {"id": 49, "cname": "Bosnia and Herzegovina", "country_id": "387"},
    {"id": 48, "cname": "Puerto Rico", "country_id": "1787"},
    {"id": 47, "cname": "Iceland", "country_id": "354"},
    {"id": 46, "cname": "Benin", "country_id": "229"},
    {"id": 45, "cname": "Bulgaria", "country_id": "359"},
    {"id": 55, "cname": "Burkina Faso", "country_id": "226"},
    {"id": 56, "cname": "Burundi", "country_id": "257"},
    {"id": 66, "cname": "French Polynesia", "country_id": "689"},
    {"id": 65, "cname": "Faroe Islands", "country_id": "298"},
    {"id": 64, "cname": "Eritrea", "country_id": "291"},
    {"id": 63, "cname": "Ecuador", "country_id": "593"},
    {"id": 62, "cname": "Dominican Republic", "country_id": "1809"},
    {"id": 61, "cname": "Dominica", "country_id": "1767"},
    {"id": 60, "cname": "Togo", "country_id": "228"},
    {"id": 59, "cname": "Diego Garcia", "country_id": "246"},
    {"id": 58, "cname": "Denmark", "country_id": "45"},
    {"id": 57, "cname": "Equatorial Guinea", "country_id": "240"},
    {"id": 44, "cname": "Bermuda", "country_id": "1441"},
    {"id": 43, "cname": "Belarus", "country_id": "375"},
    {"id": 42, "cname": "Brazil", "country_id": "55"},
    {"id": 29, "cname": "Ireland", "country_id": "353"},
    {"id": 28, "cname": "Ethiopia", "country_id": "251"},
    {"id": 27, "cname": "Egypt", "country_id": "20"},
    {"id": 26, "cname": "Azerbaijan", "country_id": "994"},
    {"id": 25, "cname": "Oman", "country_id": "968"},
    {"id": 24, "cname": "United Arab Emirates", "country_id": "971"},
    {"id": 23, "cname": "Argentina", "country_id": "54"},
    {"id": 22, "cname": "Afghanistan", "country_id": "93"},
    {"id": 21, "cname": "Algeria", "country_id": "213"},
    {"id": 20, "cname": "Albania", "country_id": "355"},
    {"id": 30, "cname": "Estonia", "country_id": "372"},
    {"id": 31, "cname": "Andorra", "country_id": "376"},
    {"id": 41, "cname": "Panama", "country_id": "507"},
    {"id": 40, "cname": "Bahrain", "country_id": "973"},
    {"id": 39, "cname": "Paraguay", "country_id": "595"},
    {"id": 38, "cname": "Pakistan", "country_id": "92"},
    {"id": 37, "cname": "Bahamas", "country_id": "1242"},
    {"id": 36, "cname": "Papua New Guinea", "country_id": "675"},
    {"id": 35, "cname": "Barbados", "country_id": "1246"},
    {"id": 34, "cname": "Austria", "country_id": "43"},
    {"id": 33, "cname": "Antigua and Barbuda", "country_id": "1268"},
    {"id": 32, "cname": "Angola", "country_id": "244"},
    {"id": 68, "cname": "Central African Republic", "country_id": "236"},
    {"id": 117, "cname": "Romania", "country_id": "40"},
    {"id": 104, "cname": "Kuwait", "country_id": "965"},
    {"id": 103, "cname": "Comoros", "country_id": "269"},
    {"id": 102, "cname": "Cayman Islands", "country_id": "1345"},
    {"id": 101, "cname": "Qatar", "country_id": "974"},
    {"id": 100, "cname": "Cameroon", "country_id": "237"},
    {"id": 99, "cname": "Réunion", "country_id": "262"},
    {"id": 98, "cname": "Zimbabwe", "country_id": "263"},
    {"id": 97, "cname": "Czech Republic", "country_id": "420"},
    {"id": 96, "cname": "Cambodia", "country_id": "855"},
    {"id": 95, "cname": "Gabon", "country_id": "241"},
    {"id": 105, "cname": "Croatia", "country_id": "385"},
    {"id": 106, "cname": "Kenya", "country_id": "254"},
    {"id": 116, "cname": "Rwanda", "country_id": "250"},
    {"id": 115, "cname": "Luxembourg", "country_id": "352"},
    {"id": 114, "cname": "Libya", "country_id": "218"},
    {"id": 113, "cname": "Liberia", "country_id": "231"},
    {"id": 112, "cname": "Lithuania", "country_id": "370"},
    {"id": 111, "cname": "Lebanon", "country_id": "961"},
    {"id": 110, "cname": "Laos", "country_id": "856"},
    {"id": 109, "cname": "Lesotho", "country_id": "266"},
    {"id": 108, "cname": "Latvia", "country_id": "371"},
    {"id": 107, "cname": "Cook Islands", "country_id": "682"},
    {"id": 94, "cname": "Ghana", "country_id": "233"},
    {"id": 93, "cname": "Guinea-Bissau", "country_id": "245"},
    {"id": 92, "cname": "Guinea", "country_id": "224"},
    {"id": 79, "cname": "Grenada", "country_id": "1473"},
    {"id": 78, "cname": "Costa Rica", "country_id": "506"},
    {"id": 77, "cname": "Colombia", "country_id": "57"},
    {"id": 76, "cname": "Democratic Republic of the Congo", "country_id": "243"},
    {"id": 75, "cname": "Republic of the Congo", "country_id": "242"},
    {"id": 74, "cname": "Gambia", "country_id": "220"},
    {"id": 73, "cname": "Falkland Islands", "country_id": "500"},
    {"id": 72, "cname": "Cape Verde", "country_id": "238"},
    {"id": 71, "cname": "Finland", "country_id": "358"},
    {"id": 70, "cname": "Fiji", "country_id": "679"},
    {"id": 80, "cname": "Greenland", "country_id": "299"},
    {"id": 81, "cname": "Cuba", "country_id": "53"},
    {"id": 91, "cname": "Kyrgyzstan", "country_id": "996"},
    {"id": 90, "cname": "Djibouti", "country_id": "253"},
    {"id": 89, "cname": "Kiribati", "country_id": "686"},
    {"id": 88, "cname": "Wake Island", "country_id": "1808"},
    {"id": 87, "cname": "Honduras", "country_id": "504"},
    {"id": 86, "cname": "Netherlands", "country_id": "31"},
    {"id": 85, "cname": "North Korea", "country_id": "850"},
    {"id": 84, "cname": "Haiti", "country_id": "509"},
    {"id": 83, "cname": "Guam", "country_id": "1671"},
    {"id": 82, "cname": "Guadeloupe", "country_id": "590"},
    {"id": 69, "cname": "Philippines", "country_id": "63"}
  ];
}
