import 'package:flutter/material.dart';

final List<Map<String, dynamic>> colorThemeTypes = [
  {'color': Colors.lime, 'label': 'Lime'},
  {'color': Colors.lightGreen, 'label': 'Light Green'},
  {'color': const Color(0xFF91AE84), 'label': 'Bean Green'},
  {'color': Colors.green, 'label': 'Green'},
  {'color': Colors.teal, 'label': 'Teal'},
  {'color': Colors.blueGrey[400], 'label': 'Blue Grey'},
  {'color': Colors.cyan, 'label': 'Cyan'},
  {'color': Colors.lightBlue, 'label': 'Light Blue'},
  {'color': Colors.blue, 'label': 'Blue'},
  {'color': const Color(0xFF191970), 'label': 'Dark Blue'},
  {'color': Colors.indigo, 'label': 'Indigo'},
  {'color': Colors.deepPurple, 'label': 'Deep Purple'},
  {'color': Colors.purple, 'label': 'Purple'},
  {'color': const Color(0xFF8C4356), 'label': 'Crimson Purple'},
  {'color': const Color(0xFFB5001D), 'label': 'Dark Red'},
  {'color': Colors.pink, 'label': 'Pink'},
  {'color': const Color(0xFFED5736), 'label': 'Red Orange'},
  {'color': const Color(0xFFFB7299), 'label': 'Light Pink'},
  {'color': Colors.red, 'label': 'Red'},
  {'color': Colors.deepOrange, 'label': 'Deep Orange'},
  {'color': const Color(0xFF993300), 'label': 'Brown'},
  {'color': Colors.brown, 'label': 'Beige'},
  {'color': Colors.orange, 'label': 'Orange'},
  {'color': Colors.amber, 'label': 'Amber'},
  {'color': Colors.yellow, 'label': 'Yellow'},
];
